import { DashboardEquipmentRow } from "./EquipmentTable.types";
import { DashboardFault } from "./FaultTable.types";

export const dashboardEquipmentRowKeys: (keyof GeneralDashboardTableRow)[] = [
  "equipment",
  "description",
  "kshirut",
  "warKshirut",
  "warTplnr",
  "conclusiveWarTplnr",
  "conclusiveWarTplnrDesc",
  "routineTplnr",
  "routineTplnrDesc",
  "warTplnrDesc",
  "isGdudManeuvering",
  "material",
  "materialFamily",
  "materialFamilyDesc",
  "mainPlatform",
  "mainPlatformDesc",
  "secPlatform",
  "secPlatformDesc",
  "isAgamForce",
  "excFromWar",
  "isLogisticForce",
  "physicalLocation",
  "physicalLocationDetails",
  "pikud",
  "pikudDesc",
  "ugda",
  "ugdaDesc",
  "utzva",
  "utzvaDesc",
  "pluga",
  "job",
  "lastUpdateTimestamp",
  "maamad",
  "maamadDesc",
  "purpose",
  "purposeDesc",
  "equipmentTask",
  "decidingNonKshirutCause",
  "tags",
];

export const dashboardFaultRowKeys: (keyof GeneralDashboardTableRow)[] = [
  "faultNum",
  "faultStatus",
  "essence",
  "equipment",
  "expectedTime",
  "contact",
  "phoneNumber",
  "dereg",
  "squad",
  "mobileAbility",
  "reqSquad",
  "note",
  "grindType",
  "availabilityInhibitor",
  "physicalLocation",
  "physicalLocationDetails",
  "faultHh",
  "faultEmz",
  "transportationType",
  "faultHhProblem",
  "faultEmzProblem",
  "createTimestamp",
  "changeTimestamp",
];

export type GeneralDashboardTableRow = Omit<
  DashboardEquipmentRow,
  "openFaults"
> &
  DashboardFault;
